config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :photos do
    resources :comments
  end
  resources :categories do 
    resources :comments
  end
  resources :comments do
    resources :comments
  end

  get "/search", to: "photos#search"
  get "/search_results", to: "photos#search_results"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # Validations
  validates :name, presence:true, uniqueness:true
  validates :cover, presence: { message: "can't be blank" }
  # Associations
  has_one_attached :cover
  has_many :photos, dependent: :nullify
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Callbacks
  after_create :increment_comments_count
  after_destroy :decrement_comments_count
  
  # Validations
  validates :body, presence:true

  # Associations
  belongs_to :commentable, polymorphic: true

  def increment_comments_count
    if commentable_type == "Photo"
      commented_photo = commentable 
      commented_photo.comments_count += 1
      commented_photo.save
    end
  end

  def decrement_comments_count
    if commentable_type == "Photo"
      commented_photo = commentable
      commented_photo.comments_count -= 1
      commented_photo.save
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  # Validations
  validates :name, presence:true, uniqueness:true
  validates :image, presence: { message: "can't be blank" }
  # Associations
  has_one_attached :image
  belongs_to :category, counter_cache: true
  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  # Jesus
  def new
    @categories = Category.new
  end

  def create
    @categories = Category.new(category_params)

    if @categories.save
      redirect_to categories_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  # Claudia
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      render "edit", status: :unprocessable_entity
    end
  end
  
  # Ximena
  # GET /categories/:id
  def show
    @category = Category.find(params[:id])
    @photos = @category.photos
    @comments = @category.comments
    @comment = Comment.new
    
    # render category/show
  end

  # DELETE /categories/:id
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to category_path, status: :see_other
  end

  private
  def category_params
    params.require(:category).permit(:name, :description, :cover)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
   if params[:category_id]
      # POST /categories/:category_id/comments
      @commentable_object = Category.find_by_id(params[:category_id])
      @category = @commentable_object
      @photos = @category.photos
      commentable_uri = "categories"
      path = category_path(@commentable_object)
   elsif params[:photo_id]
      # POST /photos/:photo_id/comments
      @commentable_object = Photo.find_by_id(params[:photo_id])
      @photo = @commentable_object
      commentable_uri = "photos"
      path = photo_path(@commentable_object)
   end

    @comment = @commentable_object.comments.create(comment_params)
    @comments = params[:category_id]?
                Category.find_by_id(params[:category_id]).comments :
                Photo.find_by_id(params[:photo_id]).comments

    if @comment.save
      redirect_to path
    else
      render "#{commentable_uri}/show", status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    params[:category_id]? 
    (redirect_to controller: 'categories', action: 'show') :
    (redirect_to controller: 'photos', action: 'show')
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # Alonso
  # GET /photos/:id
  def show
    @photo = Photo.find(params[:id])
    @comments = @photo.comments
    @comment = Comment.new
  end

  # E
  def new
    @photos = Photo.new(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end
 #Guiarse desde aqui
  def create
    @photos = Photo.new(photo_params)

    if @photos.save
      redirect_to category_path(@photos.category)
    else
      render "new", status: :unprocessable_entity
    end
  end

  # F
  def edit
    @photos = Photo.find(params[:id])
    @categories = Category.all
  end

  def update
    @photos = Photo.where(id: params[:id])[0]

    if @photos.update(photo_params)
      redirect_to category_path(@photos.category)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  # G
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to controller: 'categories', action: 'show'
  end

  # GET /search
  def search
    @photos = Photo.all
    # render search
  end

  # GET /search_results?query=x
  def search_results
    query = params[:query].downcase
    @photos = Photo.where("LOWER(name) LIKE ?", "%#{query}%")
    # render search_results
  end

  private
  def photo_params
    params.require(:photo).permit(:name, :description, :category_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
    def show_errors(record, attribute)
      errors = record.errors.full_messages_for(attribute).map do |message|
        content_tag(:span, message,class: "input__error-message") #class: "input__error-message"
      end
      puts '*'*50
      p record.errors.full_messages
      puts '*'*50
      safe_join(errors)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def show_errors(record, attribute)
    errors = record.errors.full_messages_for(attribute).map do |message|
      content_tag(:span, message)
    end

    p "==============================="
    p record.errors
    p "==============================="

    safe_join(errors)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/categories/_photo_cards.erb
<div>
  <%@photos.each do |photo|%>
    <div class="photo-card">
      <%=image_tag photo.image, class: "photo-card_cover"%>
      <div  class="photo-card_content bg-gray-100">
        <%=link_to photo.name, photo_path(photo), class: "photo-card_name heading--md"%>
        <span class="photo-card_comments"><%=photo.comments_count%> comments</span>
        <div class="options">
          <div class="option-button">
            <%=link_to image_tag("icons/edit_icon.svg"), edit_photo_path(photo), class: "option-button_link edit"%>
          </div>
          <div class="option-button">
            <%=link_to image_tag("icons/delete_icon.svg"), photo_path(photo), data: { turbo_method: :delete, 
                                                                                      turbo_confirm: "Seguro?" }, class: "option-button_link edit"%>
          </div>
        </div>
      </div>
      
    </div>
  <%end%>
</div>

app/views/categories/edit.html.erb
<section class="section-sm flex flex-column">
  <h1 class="heading">Edit category</h1>

  <% if @category.errors.any?%>
    <p>Something went wrong:</p>
    <ul>
      <% @category.errors.full_messages.each do |categorie|%>
      <li><%=categorie%></li>
      <%end%>
    </ul>
  <%end%>

  <%=form_with model: @category, class: "flex flex-column" do |f|%>
      <div class="input">
        <%=f.label :name, class: "content-xs overline"%>
        <div class="input__container">
          <%=f.text_field :name, class: "input__content"%>
        </div>
      </div>

      <div class="input">
        <%=f.label :description, class: "content-xs overline"%>
        <div class="input__container">
          <%=f.text_area :description, class: "input__content"%>
        </div>
      </div>

      <div>
        <%=f.label :cover, class: "content-xs overline"%>
        <div>
          <%=f.file_field :cover, accept: "image/png, image/jpeg"%>
        </div>
      </div>

      <%=f.submit class: "button button-primary"%>
    <%end%>
    <%=link_to "Back", categories_path, class: "button button-secondary center-text"%>
  </section>

app/views/categories/index.html.erb
<section class="start">
    <div class="spacing">
      <h1 class="heading--lg black mb-4">Categories</h1>
      <%=link_to "New Category", new_category_path, class: "button button-primary mb-4"%>
      <div>
        <%@categories.each do |category|%>
            <div class="category-card">
              <%if category.cover.attached?%>
                <%=image_tag category.cover, class: "category-card_cover"%>
              <%end%>
              <div class="category-card_content">
                <%=link_to category.name, category_path(category), class: "category-card_name heading--md"%>
                <span class="category-card_photos"><%=category.photos_count%> photos</span>
                <div class="category-card_description">
                  <%=category.description%>
                </div>
                <div class="options">
                  <div class="option-button">
                    <%=link_to image_tag("icons/edit_icon.svg"), edit_category_path(category), class: "option-button_link edit"%>
                  </div>
                  <div class="option-button">
                    <%=link_to image_tag("icons/delete_icon.svg"), category_path(category), data: { turbo_method: :delete, 
                                                                                        turbo_confirm: "Seguro?" }, class: "option-button_link delete"%>
                  </div>
                </div>
              </div>
              
            </div>
        <%end%>
      </div>
    </div>
</section>

app/views/categories/new.html.erb
<section class="section-sm flex flex-column">
  <h1 class="heading">New category</h1>
    <% if @categories.errors.any?%>
    <p>Something went wrong:</p>
    <ul>
      <% @categories.errors.full_messages.each do |categorie|%>
      <li><%=categorie%></li>
      <%end%>
    </ul>
  <%end%>

  <%=form_with model: @categories, class: "flex flex-column" do |f|%>
    <div class="input">
      <%=f.label :name, class: "content-xs overline"%>
      <div class="input__container">
        <%=f.text_field :name, placeholder: "Technology", class: "input__content"%>
      </div>
    </div>

    <div class="input">
      <%=f.label :description, class: "content-xs overline"%>
      <div class="input__container">
        <%=f.text_area :description, placeholder: "Exploring our complicated relationship with technology...", class: "input__content"%>
      </div>
    </div>

    <div>
      <%=f.label :cover, class: "content-xs overline"%>
      <div>
        <%=f.file_field :cover, accept: "image/png, image/jpeg"%>
      </div>
    </div>

    <%=f.submit class: "button button-primary"%>
  <%end%>

  <%=link_to "Back", categories_path, class: "button button-secondary center-text"%>
</section>

app/views/categories/show.html.erb
<section class="start">
  <div class="spacing">
    <div>
      <h1 class="heading--lg black mb-4"><%=@category.name%></h1>
      <p class="content-lg gray-400 mb-4"><%=@category.description%></p>
      <%=link_to "New photo", new_photo_path(category_id: @category.id), class: "button button-primary mb-4"%>
      <%=render "photo_cards"%>
    </div>
    <div> 
    <%= form_with model: [@category, @comment], method: :post, class: "flex flex-column gap-4 mb-4" do |f| %>
      <div class="input">
        <div class="input__container">
          <%=f.text_area :body, placeholder: "Type your comment...", class: "input__content"%>
        </div>
        <%=show_errors(@comment, :body)%>
      </div>
      <%=f.submit class: "button button-primary"%>
    <%end%>
    </div>
    <div>
      <h2 class="heading--md mb-4">Comments</h2>
      <%@comments.each do |comment|%>
        <div class="comment-card">
          <div class="comment-card_line"></div>
          <p class="comment-card_body"><%=comment.body%></p>
          <div class="comment-card_options">
            <span class="comment-card_date">Sent <%=time_ago_in_words(comment.created_at)%> ago</span> 
            <%=link_to image_tag("icons/delete_icon.svg"), comment_path(comment), data: { turbo_method: :delete, 
                                                                turbo_confirm: "Seguro?" }, class: "comment-card_option-button"%>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSomesplashC5w9Team07</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="container">
    <header>
      <%=link_to image_tag("brand/logo.png"), categories_path%>
      <%=link_to "Search", "/search", class: "button button-secondary"%>
    </header>
    <%= yield %>
    <footer>
      <p>Built with ♥ by</p>
      <div class="members">
        <%=link_to image_tag("icons/github.svg") + "Alonso Zevallos","https://github.com/alonsozf94", class: "member", target: "_blank"%>
        <%=link_to image_tag("icons/github.svg") + "Claudia Aybar", "https://github.com/claudiaa7p", class: "member", target: "_blank"%>
        <%=link_to image_tag("icons/github.svg") + "Jesús Tuesta", "https://github.com/jesustr20", class: "member", target: "_blank"%>
        <%=link_to image_tag("icons/github.svg") + "Ximena Calderón", "https://github.com/ximecalderon", class: "member", target: "_blank"%>
      </div>
    </footer>
  </body>
</html>

app/views/photos/_search_form.html.erb
<%=form_with url: "/search_results", method: :get, class: "flex flex-column" do |f|%>
    <h1 class="heading"><%=f.label :query, "Search"%></h1>
    <div class="input__container">
        <%=f.text_field :query, placeholder: "Search term", class: "input__content"%>
    </div>
    <%=f.submit "Search photos", class: "button button-primary"%>
<%end%>

app/views/photos/edit.html.erb
<section class="section-sm flex flex-column">
  <h1 class="heading">Edit Photos</h1>
  <% if @photos.errors.any?%>
    <p>Something went wrong:</p>
    <ul>
      <% @photos.errors.full_messages.each do |picture|%>
      <li><%=picture%></li>
      <%end%>
    </ul>
  <%end%>

  <%=form_with model: @photos, class: "flex flex-column" do |f|%>
      <div class="input">
        <%=f.label :name, "Title", class: "content-xs overline"%>
        <div class="input__container">
          <%=f.text_field :name, class: "input__content"%>
        </div>
      </div>

      <div class="input">
        <%=f.label :description, class: "content-xs overline"%>
        <div class="input__container">
          <%=f.text_area :description, class: "input__content"%>
        </div>
      </div>

      <div class="select">
        <%=f.label :category_id, class: "content-xs overline"%>
        <%= f.collection_select :category_id, Category.order(:name), :id, :name, { selected: @photos.category_id }, class: "select__input" %>
      </div>


      <div>
        <%=f.label :image, class: "content-xs overline"%>
        <div>
          <%=f.file_field :image, accept: "image/png, image/jpeg"%>
        </div>
      </div>

      <%=f.submit "Edit Photo", class: "button button-primary"%>
    <%end%>

    <%= link_to "Back", category_path(@photos.category), class: "button button-secondary center-text" %>
  </section>

app/views/photos/new.html.erb
<section class="section-sm flex flex-column">
  <h1 class="heading">New photo</h1>
 <% if @photos.errors.any?%>
    <p>Something went wrong:</p>
    <ul>
      <% @photos.errors.full_messages.each do |photo|%>
      <li><%=photo%></li>
      <%end%>
    </ul>
  <%end%>

    <%=form_with model: @photos, class: "flex flex-column gap-4 mb-4" do |f|%>
    <div class="input">
      <%=f.label :name, class: "content-xs overline"%>
      <div class="input__container">
        <%=f.text_field :name, placeholder: "Big mountain", class: "input__content"%>
      </div>
    </div>

    <div class="input">
      <%=f.label :description, class: "content-xs overline"%>
      <div class="input__container">
        <%=f.text_area :description, placeholder: "Photo taken on...", class: "input__content"%>
      </div>
    </div>

    <div class="select">
      <%=f.label :category_id, class: "content-xs overline"%>
      <%= f.collection_select :category_id, Category.order(:name), :id, :name, { selected: @photos.category_id }, class: "select__input" %>
    </div>
  
    <div>
      <%=f.label :image, class: "content-xs overline"%>
      <div>
        <%=f.file_field :image, accept: "image/png, image/jpeg"%>
      </div>
    </div>

      <%=f.submit class: "button button--secondary"%>
    <%end%>
  <%= link_to "Back", category_path(@photos.category) %>

app/views/photos/search.html.erb
<section class="section-sm">
  <div class="container input">
    <%=render "search_form"%>
  </div>
</section>

app/views/photos/search_results.html.erb
<section class="section-sm">
  <div class="container input">
    <%=render "search_form"%>
  </div>
  <%=render "categories/photo_cards"%>
</section>

app/views/photos/show.html.erb
<section class="start">
  <div class="spacing">
    <p class="heading--lg black mb-1"><%=@photo.name%></p>
    <p class="content-xl gray-400 mb-1"><%=@photo.description%></p>
    <p class="content-lg gray-300 mb-1">Updated at <%=time_ago_in_words(@photo.updated_at)%> ago</p>
    <div class="mb-4"><%=image_tag @photo.image%></div>
    <%= form_with model: [@photo, @comment], method: :post, class: "flex flex-column gap-4 mb-4" do |f| %>
      <div class="input">
        <div class="input__container">
          <%=f.text_area :body, placeholder: "Type your comment...", class: "input__content"%>
        </div>
        <%=show_errors(@comment, :body)%>
      </div>
      <%=f.submit class: "button button-primary"%>
    <%end%>
    <div>
      <h2 class="heading--md mb-4">Comments</h2>
      <%@comments.each do |comment|%>
        <div class="comment-card">
          <div class="comment-card_line"></div>
          <p class="comment-card_body"><%=comment.body%></p>
          <div class="comment-card_options">
            <span class="comment-card_date">Sent <%=time_ago_in_words(comment.created_at)%> ago</span> 
            <%=link_to image_tag("icons/delete_icon.svg"), comment_path(comment), data: { turbo_method: :delete, 
                                                                turbo_confirm: "Seguro?" }, class: "comment-card_option-button"%>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>